/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mysql.cdc.intrusion_details;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Key extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8963083952469248681L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Key\",\"namespace\":\"mysql.cdc.intrusion_details\",\"fields\":[{\"name\":\"reference_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"connect.name\":\"mysql.cdc.intrusion_details.Key\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Key> ENCODER =
      new BinaryMessageEncoder<Key>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Key> DECODER =
      new BinaryMessageDecoder<Key>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Key> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Key> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Key>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Key to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Key from a ByteBuffer. */
  public static Key fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String reference_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Key() {}

  /**
   * All-args constructor.
   * @param reference_id The new value for reference_id
   */
  public Key(java.lang.String reference_id) {
    this.reference_id = reference_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reference_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reference_id = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reference_id' field.
   * @return The value of the 'reference_id' field.
   */
  public java.lang.String getReferenceId() {
    return reference_id;
  }


  /**
   * Creates a new Key RecordBuilder.
   * @return A new Key RecordBuilder
   */
  public static mysql.cdc.intrusion_details.Key.Builder newBuilder() {
    return new mysql.cdc.intrusion_details.Key.Builder();
  }

  /**
   * Creates a new Key RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Key RecordBuilder
   */
  public static mysql.cdc.intrusion_details.Key.Builder newBuilder(mysql.cdc.intrusion_details.Key.Builder other) {
    return new mysql.cdc.intrusion_details.Key.Builder(other);
  }

  /**
   * Creates a new Key RecordBuilder by copying an existing Key instance.
   * @param other The existing instance to copy.
   * @return A new Key RecordBuilder
   */
  public static mysql.cdc.intrusion_details.Key.Builder newBuilder(mysql.cdc.intrusion_details.Key other) {
    return new mysql.cdc.intrusion_details.Key.Builder(other);
  }

  /**
   * RecordBuilder for Key instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Key>
    implements org.apache.avro.data.RecordBuilder<Key> {

    private java.lang.String reference_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mysql.cdc.intrusion_details.Key.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reference_id)) {
        this.reference_id = data().deepCopy(fields()[0].schema(), other.reference_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Key instance
     * @param other The existing instance to copy.
     */
    private Builder(mysql.cdc.intrusion_details.Key other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.reference_id)) {
        this.reference_id = data().deepCopy(fields()[0].schema(), other.reference_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'reference_id' field.
      * @return The value.
      */
    public java.lang.String getReferenceId() {
      return reference_id;
    }

    /**
      * Sets the value of the 'reference_id' field.
      * @param value The value of 'reference_id'.
      * @return This builder.
      */
    public mysql.cdc.intrusion_details.Key.Builder setReferenceId(java.lang.String value) {
      validate(fields()[0], value);
      this.reference_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'reference_id' field has been set.
      * @return True if the 'reference_id' field has been set, false otherwise.
      */
    public boolean hasReferenceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'reference_id' field.
      * @return This builder.
      */
    public mysql.cdc.intrusion_details.Key.Builder clearReferenceId() {
      reference_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Key build() {
      try {
        Key record = new Key();
        record.reference_id = fieldSetFlags()[0] ? this.reference_id : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Key>
    WRITER$ = (org.apache.avro.io.DatumWriter<Key>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Key>
    READER$ = (org.apache.avro.io.DatumReader<Key>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
